doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                host: '%env(DB_HOST)%'
                port: '%env(DB_PORT)%'
                dbname: '%env(DB_NAME)%'
                user: '%env(DB_USER)%'
                password: '%env(DB_PASS)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
