version: '3.7'

services:
  php:
    container_name: balance_php
    build: ./docker/php/
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - postgres
    working_dir: /var/www/app
    ports:
      - 9001:9001

  nginx:
    container_name: balance_nginx
    image: nginx:alpine
    depends_on:
      - php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  postgres:
    container_name: balance_postgres
    image: postgres:11
    ports:
      - 5434:5432
    working_dir: /var/www/app
    restart: on-failure
    environment:
      POSTGRES_DB: balance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
